### ISSUE TITLE
Include contributors and license in the README

### ISSUE THREAD

**Issue by geisserf** [geisserf/lemon-dd#3]
Contributors are as far as I know:
- Florian Geißer (core developer 2017-2019)
- Benedict Wright (core developer 2017-2019)
- David Speck (implemented variable ordering heuristic support, 2018)
- Ece Tavaslı (HiWi 2018)

For the license, we include parts of the following projects and have to see what license they use: 
- Boost
- Clang (but only as a separate submodule)
- The catamorph parts which form the backbone of the expression class is based on [this tutorial](https://deque.blog/2017/01/30/catamorph-your-dsl-c-port/). I think it is the best to ask the blod maintainer if he is ok with parts of his code being used and to give him credit in the readme.

**Comment by geisserf** [comment]
Clang itself also only has the Boost library as license, so if we just add the boost library we should be covered. Personally I'm fine with using the boost license as our only license.
What do you think @digitalw ?

**Comment by digitalw** [comment]
Looks good. what I could not see if it allows commercial us of the library. But i would assume so.

**Comment by geisserf** [comment]
Yes, it does indeed.

**Comment by digitalw** [comment]
Then i am fine with that licence model

**Comment by geisserf** [comment]
Issue was solved with de18d60
